openapi: "3.0.0"
info:
  version: 1.0.0
  title: Orchestrator API
  description: API to control Benchmark Execution
  termsOfService: https://host.tld/terms/
  contact:
    name: Clemens Künzel
    email: me@cleem.de
    url: https://host.tld

servers:
  - url: http://localhost:8081
  - url: https://host.tld
paths:
  /rest/preload:
    post:
      description: Accepts Preload Request
      operationId: preload
      tags:
        - OrchestratorPreload
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "model/preloadRequest.json"
      responses:
        '200':
          description: The Preload response
          content:
            application/json:
              schema:
                $ref: "model/preloadResponse.json"
  /rest/ping:
    get:
      description: Returns Ping response (Pong)
      operationId: ping
      tags:
        - OrchestratorPing
      responses:
        '200':
          description: The Ping response (Pong)
          content:
            application/json:
              schema:
                $ref: "model/pingResponse.json"