openapi: "3.0.0"
info:
  version: 1.0.0
  title: Orchestrator API
  description: API to control Benchmark Execution
  termsOfService: https://host.tld/terms/
  contact:
    name: Clemens Künzel
    email: me@cleem.de
    url: https://host.tld

servers:
  - url: http://localhost:8081
  - url: https://host.tld
paths:
  /rest/setup:
    post:
      description: Accepts Setup Request
      operationId: setup
      tags:
        - OrchestratorSetup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "model/orchestrator/orchestratorSetupRequest.json"
      responses:
        '200':
          description: The Setup response
          content:
            application/json:
              schema:
                $ref: "model/orchestrator/orchestratorSetupResponse.json"
  /rest/reset:
    get:
      description: Returns reset response
      operationId: reset
      tags:
        - OrchestratorReset
      responses:
        '200':
          description: The orchestrator reset response
          content:
            application/json:
              schema:
                $ref: "model/resetResponse.json"
  /rest/start:
    get:
      description: Returns StartStop response
      operationId: start
      tags:
        - OrchestratorStart
      responses:
        '200':
          description: The orchestrator startStop response
          content:
            application/json:
              schema:
                $ref: "model/startStopResponse.json"
  /rest/stop:
    get:
      description: Returns StartStop response
      operationId: stop
      tags:
        - OrchestratorStop
      responses:
        '200':
          description: The orchestrator startStop response
          content:
            application/json:
              schema:
                $ref: "model/startStopResponse.json"
  /rest/collect:
    post:
      description: Accepts Benchmark Result Request
      operationId: collect
      tags:
        - OrchestratorCollect
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "model/result/benchmarkResultRequest.json"
      responses:
        '200':
          description: The Benchmark Result Response
          content:
            application/json:
              schema:
                $ref: "model/result/benchmarkResultResponse.json"
  /rest/results:
    get:
      description: Returns partial and complete results
      operationId: results
      tags:
        - OrchestratorResults
      responses:
        '200':
          description: The Orchestrator Result Response
          content:
            application/json:
              schema:
                $ref: "model/orchestrator/orchestratorResultResponse.json"
  /rest/ping:
    get:
      description: Returns Ping response (Pong)
      operationId: ping
      tags:
        - OrchestratorPing
      responses:
        '200':
          description: The Ping response (Pong)
          content:
            application/json:
              schema:
                $ref: "model/pingResponse.json"