openapi: "3.0.0"
info:
  version: 1.0.0
  title: Worker API
  description: API to control Worker Execution
  termsOfService: https://host.tld/terms/
  contact:
    name: Clemens Künzel
    email: me@cleem.de
    url: https://host.tld

servers:
  - url: http://localhost:8082
  - url: https://host.tld
paths:
  /rest/setup:
    post:
      description: Accepts Setup Request
      operationId: setup
      tags:
        - WorkerSetup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "model/worker/workerSetupRequest.json"
      responses:
        '200':
          description: The Setup response
          content:
            application/json:
              schema:
                $ref: "model/worker/workerSetupResponse.json"
  /rest/reset:
    get:
      description: Returns reset response
      operationId: reset
      tags:
        - WorkerReset
      responses:
        '200':
          description: The worker reset response
          content:
            application/json:
              schema:
                $ref: "model/resetResponse.json"
  /rest/start:
    get:
      description: Returns StartStop response
      operationId: start
      tags:
        - WorkerStart
      responses:
        '200':
          description: The worker startStop response
          content:
            application/json:
              schema:
                $ref: "model/startStopResponse.json"
  /rest/stop:
    get:
      description: Returns StartStop response
      operationId: stop
      tags:
        - WorkerStop
      responses:
        '200':
          description: The worker startStop response
          content:
            application/json:
              schema:
                $ref: "model/startStopResponse.json"
  /rest/ping:
    get:
      description: Returns Ping response (Pong)
      operationId: ping
      tags:
        - WorkerPing
      responses:
        '200':
          description: The Ping response (Pong)
          content:
            application/json:
              schema:
                $ref: "model/pingResponse.json"