server:
  port: 8080

application:
  banner:
    title: TSDB Benchmark Workload Generator Microservice
    copyright: cleem
    year: 2023
  errors:
    logStackTrace: true


spring:
  application:
    name: generator